fix: test refacto yml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -1,4 +1,3 @@
-# Liste des Cloud Builders : https://console.cloud.google.com/gcr/images/cloud-builders/GLOBAL
 steps:
 - name: "noobzik/uv-gcp-cloud-build"
   id: CI
@@ -7,24 +6,28 @@ steps:
   env:
     - PROJECT_ID=$PROJECT_ID
   args:
-  - -c
-  - |
-    echo "$$SERVICE_ACCOUNT" > service_account.json
-    if ! gcloud auth activate-service-account --key-file=service_account.json; then
-      echo "ERROR: gcloud authenfication failed!"
-      exit 1
-    fi
-    gcloud config set project "$PROJECT_ID"
-    chmod a+x install.sh &&
-    ./install.sh &&
-    source .venv/bin/activate &&
-    export GOOGLE_APPLICATION_CREDENTIALS=service_account.json &&
-    export PYTHONPATH=$(pwd)/src &&
-    python -m pytest ./tests/pipelines/data_processing &&
-    python -m pytest ./tests/pipelines/model_training
+    - -c
+    - |
+      mkdir -p conf/local
+      echo "$$SERVICE_ACCOUNT" > conf/local/service_account.json
+      if ! gcloud auth activate-service-account --key-file=conf/local/service_account.json; then
+        echo "ERROR: gcloud authenfication failed!"
+        exit 1
+      fi
+      gcloud config set project "$PROJECT_ID"
+
+      chmod a+x install.sh
+      ./install.sh
+      source .venv/bin/activate
+
+      # Facultatif : pour le code Python qui attend la var GOOGLE_APPLICATION_CREDENTIALS
+      export GOOGLE_APPLICATION_CREDENTIALS=conf/local/service_account.json
+
+      python -m pytest ./tests/pipelines/data_processing
+      python -m pytest ./tests/pipelines/model_training
 
 logs_bucket: gs://bucket_projet_mlops/logs_build_cloud_build
 availableSecrets:
   secretManager:
-  - versionName: projects/$PROJECT_ID/secrets/cloudbuild/versions/1
+  - versionName: projects/$PROJECT_ID/secrets/cloud-build/versions/1
     env: SERVICE_ACCOUNT
